apiVersion: apps/v1
kind: Deployment

metadata:
  name: bakend-deploy
  labels:
    run: backend

spec:
  replicas: 2
  template:
    metadata:
      name: backend-pod
      labels:
        run: backend
    spec:
      containers:
        - name: wordpress
          image: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              # curl mysql-wordpress
              value: mysql-wordpress

