apiVersion: v1
kind: Service

metadata:
  name: mysql-service

spec:
  type: ClusterIP
  clusterIP: "10.96.15.1"
  selector:
    app: mysql-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
