apiVersion: v1
kind: Service

metadata:
  name: wordpress-service

spec:
# v1: Cluster IP
#  type: ClusterIP
# v2: Node Port
  type: NodePort
  clusterIP: "10.96.5.2"
  selector:
    app: wordpress-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31111
