apiVersion: v1
kind: Service

metadata:
  name: echo-service-load-balancer

spec:
  type: LoadBalancer
  selector:
    pod: hello-pod
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
