apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql-deploy

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql-app
    spec:
      containers:
        - name: mysql-pod
          image: mysql:5.7
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "true"
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_PASSWORD
              value: "wordpress$123"
            - name: MYSQL_DATABASE
              value: wordpress
          ports:
            - containerPort: 3306
