apiVersion: apps/v1
kind: Deployment

metadata:
  name: deploy-nginx

spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: deploy-container
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service

metadata:
  name: svc-nginx
  labels:
    app: nginx

spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31111
      protocol: TCP
  selector:
    app: nginx
