apiVersion: v1
kind: Pod

metadata:
  name: test-pvc-pod

spec:
  containers:
    - name: test-pod
      image: busybox
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "touch /mnt/test && exit 0 || exit 1"
      volumeMounts:
        - name: test-pvc
          mountPath: "/mnt"
  volumes:
    - name: test-pvc
      persistentVolumeClaim:
        claimName: test-pvc
  restartPolicy: "Never"
