apiVersion: v1
kind: Service

metadata:
  # Los servicios generan DNS automáticos basados en el nombre servicio
  name: token-service

spec:
  type: ClusterIP
  clusterIP: "10.96.20.1"
  selector:
    app: token-app
  ports:
    - protocol: TCP
      # Cluster-IP Port
#      port: 8080
      port: 80
      # Pod Port
      targetPort: 80
