apiVersion: v1
kind: Service

metadata:
  name: token-generator-svc-node-port
  labels:
    app: token-generator-app

spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31123
      protocol: TCP
  selector:
    app: token-generator-app
