apiVersion: v1
kind: Service

metadata:
  name: token-generator-svc-cluster-ip
  labels:
    app: token-generator-app

spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: token-generator-app