kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster304

networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.244.0.0/16"
  disableDefaultCNI: FALSE
  # kubeProxyMode: "ipvs"

nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /tmp/foo/
        containerPath: /tmp/bar/
        readOnly: true
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
      - containerPort: 31111
        hostPort: 8081
      - containerPort: 31222
        hostPort: 8082
      - containerPort: 31333
        hostPort: 8083
      - containerPort: 31444
        hostPort: 8084
  - role: worker
  - role: worker


